---
sidebar: sidebar 
permalink: reference-limitations-azure.html 
keywords: limitations, ha, azure, pay-as-you-go, paygo, cloud solution provider, nfsv3 
summary: Estas limitaciones conocidas son específicas de Cloud Volumes ONTAP en Microsoft Azure. 
---
= Limitaciones conocidas de Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Las siguientes limitaciones conocidas son específicas de Cloud Volumes ONTAP en Microsoft Azure. No olvide revisar también link:reference-limitations.html["Limitaciones en todos los proveedores de cloud"].



== Limitaciones del uso de extensiones de Azure VM

Cloud Volumes ONTAP no es compatible con las extensiones de máquinas virtuales de Azure ni con aplicaciones de máquinas virtuales en una implementación. El uso de Cloud Volumes ONTAP en Azure con extensiones de VM provoca retrasos en las operaciones y NetApp recomienda evitarlos.



== Limitaciones de Flash Cache

El tipo de máquina virtual Standard_L8S_v2 incluye almacenamiento NVMe local, el cual Cloud Volumes ONTAP utiliza como _Flash Cache_. Tenga en cuenta las siguientes limitaciones para Flash Cache:

* La compresión debe deshabilitarse en todos los volúmenes para aprovechar las mejoras de rendimiento de Flash Cache.
+
No puede elegir eficiencia de almacenamiento al crear un volumen desde BlueXP o puede crear un volumen y, a continuación, hacerlo http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-vsmg/GUID-8508A4CB-DB43-4D0D-97EB-859F58B29054.html["Deshabilite la compresión de datos mediante la CLI"^].

* Cloud Volumes ONTAP no admite el recalentamiento de la caché después de un reinicio.




== Limitaciones de ALTA DISPONIBILIDAD

Las siguientes limitaciones afectan a los pares de alta disponibilidad de Cloud Volumes ONTAP en Microsoft Azure:

* NFSv4 no es compatible. NFSv3 es compatible.
* En algunas regiones no se admiten pares DE HA.
+
https://cloud.netapp.com/cloud-volumes-global-regions["Consulte la lista de regiones de Azure admitidas"^]


